# Generated by Django 5.2.10 on 2026-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_avatar',
            field=models.CharField(choices=[('avatar1', 'Avatar 1'), ('avatar2', 'Avatar 2'), ('avatar3', 'Avatar 3'), ('avatar4', 'Avatar 4'), ('avatar5', 'Avatar 5')], default='avatar1', max_length=20),
        ),
    ]
