# Generated by Django 5.2.10 on 2026-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('RENT', 'Rent'), ('EMI', 'EMI'), ('FUEL', 'Fuel'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
